config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  #Conacyt Requirements

  get 'client/persona_name', to: 'conacyt_catalogs#persona_name'
  get 'client/autor', to: 'conacyt_catalogs#autor'
  get 'padron', to: 'conacyt_stats#padron'
  get 'ranking/articulos', to: 'conacyt_stats#articulos'
  get 'ranking/autores', to: 'conacyt_stats#autores'
  get 'descargas', to: 'conacyt_stats#descargas'

  #End Conacyt Requirements

  Hydra::BatchEdit.add_routes(self)
  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :oai_provider, BlacklightOaiProvider::Routes::Provider.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => 'registrations' }

  mount CurationConcerns::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'sufia/homepage#index'
  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  concern :exportable, Blacklight::Routes::Exportable.new
  resources :featured_collections
  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  get '/gatekeeper/:ident', to: 'iiif_gatekeeper#show', as: 'gatekeeper', constraints: { ident: /[-A-Za-z0-9,_\.\/]+/ }

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resources :import_field_mappings

  resources :imports do
    member do
      post 'start'
      post 'undo'
      post 'resume'
      post 'finalize'
      get 'report'
      get 'image_preview/:row', controller: 'imports', action: :image_preview, as: 'image_preview'
      get 'row-preview/:row_num', controller: 'imports', action: :row_preview, as: 'row_preview'
    end

    collection do
      post 'browse'
    end
  end

  Hydra::BatchEdit.add_routes(self)

  resources :units
  resources :memberships, only: :destroy

  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/jobs'
  end

  # Handle routes that existed in Sufia < 7
  #   e.g. https://library.osu.edu/ims/files/gm80hv36p
  get '/files/:id', to: redirect('concern/generic_works/%{id}')

  # Disable Sufia contact, help, and about pages
  get '/about', to: 'application#not_found'
  get '/contact', to: 'application#not_found'
  get '/help', to: 'application#not_found'

  # API
  namespace :api, defaults: { format: :json }, constraints: { format: /(json|xml)/ } do
    api_version(module: "V1",
                path: { value: "v1" },
                header: { name: "Accept", value: "application/vnd.library.osu.edu; version=1" },
                default: true) do

      concerns :oai_provider, path: '/oai', controller: 'oai', format: 'xml'
      resources :properties, only: [:index, :show]
    end
  end

  # This must be the very last route in the file because it has a catch-all route for 404 errors.
  # This behavior seems to show up only in production mode.
  mount Sufia::Engine => '/'

  # Add Units tab to the dashboard
  Sufia::Engine.routes.draw do
    scope :dashboard do
      get '/units',            controller: 'my/units', action: :index, as: 'dashboard_units'
      get '/units/page/:page', controller: 'my/units', action: :index
      get '/units/facet/:id',  controller: 'my/units', action: :facet, as: 'dashboard_units_facet'
    end
  end
end

app/models/collection.rb
# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include CurationConcerns::BasicMetadata

  property :unit, predicate: ::RDF::URI.new('https://library.osu.edu/ns#unit'), multiple: false do |index|
    index.as :stored_searchable
  end
end

app/views/collections/_show_actions.html.erb
<h2 class="sr-only"><%= t('sufia.collection.actions.header') %></h2>
<div class="actions-controls-collections">
    <% if can? :edit, presenter.solr_document %>
      <%= link_to t('sufia.collection.actions.edit.label'),
                  edit_collection_path(presenter),
                  title: t('sufia.collection.actions.edit.desc'),
                  class: 'btn btn-default' %>
      <%= link_to t('sufia.collection.actions.add_works.label'),
                  sufia.dashboard_works_path(add_files_to_collection: presenter.id),
                  title: t('sufia.collection.actions.add_works.desc'),
                  class: 'btn btn-default' %>
    <%end %>

    <% if can? :destroy, presenter.solr_document %>
      <%= link_to t('sufia.collection.actions.delete.label'),
                  collection_path(presenter),
                  title: t('sufia.collection.actions.delete.desc'),
                  class: 'btn btn-danger',
                  data: { confirm: t('sufia.collection.actions.delete.confirmation'),
                          method: :delete } %>
    <% end %>
    <% if presenter.display_feature_link? %>
      <%= link_to "Feature", featured_collections_path(id: presenter.id), remote: true,
          method: :post, class: 'btn btn-default' %>
    <% end %>
    <% if presenter.display_unfeature_link? %>
      <%= link_to "Unfeature", featured_collection_path(presenter, format: :json),
          data: {behavior: 'unfeature'}, method: :delete, id: 'unfeatureLink', name: 'unfeatureLink', class: 'btn btn-default' %>
    <% end %>
</div>

app/views/collections/show.html.erb
<% provide :page_title, construct_page_title(@presenter.title) %>
<div itemscope itemtype="http://schema.org/CollectionPage" class="row">
  <div class="col-sm-9 pull-right">
    <header>
      <%= render 'collection_title', presenter: @presenter %>
    </header>
    <%= render 'collection_description', presenter: @presenter %>

    <% unless has_collection_search_parameters? %>
      <%= render 'collections/show_descriptions' %>
    <% end %>
  </div>
  <div class="col-sm-3">
    <%= render 'collections/media_display', presenter: @presenter %>
    <% unless has_collection_search_parameters? %>
      <%= render 'collections/show_actions', presenter: @presenter %>
    <% end %>
  </div>
</div>

<div class="row">
  <h2 class="col-xs-6 col-md-7 col-lg-6">
    <% if has_collection_search_parameters? %>
        Search Results within this Collection
    <% else %>
        Items in this Collection
    <% end %>
  </h2>
  <div class="col-xs-6 col-md-5 col-lg-6"><%= render 'search_form', presenter: @presenter %></div>
</div>

<%= render 'sort_and_per_page', collection: @presenter %>

<%= render_document_index @member_docs %>

<%= render 'paginate' %>