config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  #Conacyt Requirements

  get 'client/persona_name', to: 'conacyt_catalogs#persona_name'
  get 'client/autor', to: 'conacyt_catalogs#autor'
  get 'padron', to: 'conacyt_stats#padron'
  get 'ranking/articulos', to: 'conacyt_stats#articulos'
  get 'ranking/autores', to: 'conacyt_stats#autores'
  get 'descargas', to: 'conacyt_stats#descargas'

  #End Conacyt Requirements

  Hydra::BatchEdit.add_routes(self)
  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :oai_provider, BlacklightOaiProvider::Routes::Provider.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => 'registrations' }

  mount CurationConcerns::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'sufia/homepage#index'
  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  concern :exportable, Blacklight::Routes::Exportable.new
  resources :featured_collections
  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  get '/gatekeeper/:ident', to: 'iiif_gatekeeper#show', as: 'gatekeeper', constraints: { ident: /[-A-Za-z0-9,_\.\/]+/ }

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resources :import_field_mappings

  resources :imports do
    member do
      post 'start'
      post 'undo'
      post 'resume'
      post 'finalize'
      get 'report'
      get 'image_preview/:row', controller: 'imports', action: :image_preview, as: 'image_preview'
      get 'row-preview/:row_num', controller: 'imports', action: :row_preview, as: 'row_preview'
    end

    collection do
      post 'browse'
    end
  end

  Hydra::BatchEdit.add_routes(self)

  resources :units
  resources :memberships, only: :destroy

  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/jobs'
  end

  # Handle routes that existed in Sufia < 7
  #   e.g. https://library.osu.edu/ims/files/gm80hv36p
  get '/files/:id', to: redirect('concern/generic_works/%{id}')

  # Disable Sufia contact, help, and about pages
  get '/about', to: 'application#not_found'
  get '/contact', to: 'application#not_found'
  get '/help', to: 'application#not_found'

  # API
  namespace :api, defaults: { format: :json }, constraints: { format: /(json|xml)/ } do
    api_version(module: "V1",
                path: { value: "v1" },
                header: { name: "Accept", value: "application/vnd.library.osu.edu; version=1" },
                default: true) do

      concerns :oai_provider, path: '/oai', controller: 'oai', format: 'xml'
      resources :properties, only: [:index, :show]
    end
  end

  # This must be the very last route in the file because it has a catch-all route for 404 errors.
  # This behavior seems to show up only in production mode.
  mount Sufia::Engine => '/'

  # Add Units tab to the dashboard
  Sufia::Engine.routes.draw do
    scope :dashboard do
      get '/units',            controller: 'my/units', action: :index, as: 'dashboard_units'
      get '/units/page/:page', controller: 'my/units', action: :index
      get '/units/facet/:id',  controller: 'my/units', action: :facet, as: 'dashboard_units_facet'
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  include Sufia::DashboardHelperBehavior

  # Override to add units controller
  def on_my_works?
    params[:controller].match(/^my\/(works|units)/)
  end

  def current_dashboard_tab
    params[:controller].match(/^my\/(.+)/).try(:[], 1).try(:to_sym)
  end
end

app/views/dashboard/_index_partials/_heading_actions.html.erb
<div class="col-xs-12 heading-row">
  <div class="row">
    <% if can?(:create, Sufia.primary_work_type) %>
        <div class="col-xs-6 col-sm-2 heading-tile">
          <% classification = CurationConcerns::QuickClassificationQuery.new(current_user) %>
          <% classification.each do |concern| %>
              <%= link_to(new_polymorphic_path([main_app, concern]),
                          class: "item-option contextual-quick-classify #{dom_class(concern, 'new').gsub('_', '-')}",
                          role: 'menuitem'
                  ) do %>
                  <span class="glyphicon glyphicon-upload"></span>
                  <%= I18n.t("sufia.dashboard.create_work", work_type: concern.human_readable_type) %>
              <% end %>
          <% end %>
        </div>
    <% end %>
    <!-- <% if can?(:create, Collection) %>
        <div class="col-xs-6 col-sm-2 heading-tile">
          <%= link_to new_collection_path, id: "hydra-collection-add" do %>
              <span class="glyphicon glyphicon-plus"></span>
              <%= t("sufia.dashboard.create_collection") %>
          <% end %>
        </div>
    <% end  %>
    <div class="col-xs-6 col-sm-2 heading-tile">
      <%= link_to sufia.dashboard_collections_path, id: "hydra-collection-view" do %>
          <span class="glyphicon glyphicon-th"></span>
          <%= t("sufia.dashboard.view_collections") %>
      <% end %>
    </div> -->
    <div class="col-xs-6 col-sm-2 heading-tile">
      <%= link_to sufia.dashboard_units_path  do %>
          <span class="glyphicon glyphicon-eye-open"></span>
          <%= t("sufia.dashboard.view_works") %>
      <% end %>
    </div>
  </div>
</div>