config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  #Conacyt Requirements

  get 'client/persona_name', to: 'conacyt_catalogs#persona_name'
  get 'client/autor', to: 'conacyt_catalogs#autor'
  get 'padron', to: 'conacyt_stats#padron'
  get 'ranking/articulos', to: 'conacyt_stats#articulos'
  get 'ranking/autores', to: 'conacyt_stats#autores'
  get 'descargas', to: 'conacyt_stats#descargas'

  #End Conacyt Requirements

  Hydra::BatchEdit.add_routes(self)
  mount Blacklight::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :oai_provider, BlacklightOaiProvider::Routes::Provider.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', :registrations => 'registrations' }

  mount CurationConcerns::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'sufia/homepage#index'
  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  concern :exportable, Blacklight::Routes::Exportable.new
  resources :featured_collections
  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  get '/gatekeeper/:ident', to: 'iiif_gatekeeper#show', as: 'gatekeeper', constraints: { ident: /[-A-Za-z0-9,_\.\/]+/ }

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  resources :import_field_mappings

  resources :imports do
    member do
      post 'start'
      post 'undo'
      post 'resume'
      post 'finalize'
      get 'report'
      get 'image_preview/:row', controller: 'imports', action: :image_preview, as: 'image_preview'
      get 'row-preview/:row_num', controller: 'imports', action: :row_preview, as: 'row_preview'
    end

    collection do
      post 'browse'
    end
  end

  Hydra::BatchEdit.add_routes(self)

  resources :units
  resources :memberships, only: :destroy

  authenticate :user, -> (u) { u.admin? } do
    mount Sidekiq::Web => '/jobs'
  end

  # Handle routes that existed in Sufia < 7
  #   e.g. https://library.osu.edu/ims/files/gm80hv36p
  get '/files/:id', to: redirect('concern/generic_works/%{id}')

  # Disable Sufia contact, help, and about pages
  get '/about', to: 'application#not_found'
  get '/contact', to: 'application#not_found'
  get '/help', to: 'application#not_found'

  # API
  namespace :api, defaults: { format: :json }, constraints: { format: /(json|xml)/ } do
    api_version(module: "V1",
                path: { value: "v1" },
                header: { name: "Accept", value: "application/vnd.library.osu.edu; version=1" },
                default: true) do

      concerns :oai_provider, path: '/oai', controller: 'oai', format: 'xml'
      resources :properties, only: [:index, :show]
    end
  end

  # This must be the very last route in the file because it has a catch-all route for 404 errors.
  # This behavior seems to show up only in production mode.
  mount Sufia::Engine => '/'

  # Add Units tab to the dashboard
  Sufia::Engine.routes.draw do
    scope :dashboard do
      get '/units',            controller: 'my/units', action: :index, as: 'dashboard_units'
      get '/units/page/:page', controller: 'my/units', action: :index
      get '/units/facet/:id',  controller: 'my/units', action: :facet, as: 'dashboard_units_facet'
    end
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  include FedoraObjectAssociations

  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user
  belongs_to :admin_policy

  before_create :add_admin_policy

  has_attached_file :image, styles: { landing: "300x200#", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.jpg"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :key, :name, presence: true
  validates :key, uniqueness: true, format: { with: /\A[-A-Za-z1-9]+\z/, message: "only allows letters, numbers and hyphens" }

  accepts_nested_attributes_for :memberships, allow_destroy: true

  scope :visible, -> { where(visible: true) }

  def self.spec_from_key(key)
    "unit:#{key}"
  end

  def spec
    self.class.spec_from_key(key)
  end

  private

  def add_admin_policy
    create_admin_policy default_permissions_attributes: [{ type: "group", access: "edit", name: key }]
  end
end

app/controllers/my/units_controller.rb
module My
  class UnitsController < MyController
    def search_builder_class
      ::MyUnitsSearchBuilder
    end

    def index
      super
      @selected_tab = 'units'
    end

    protected

    def search_action_url(*args)
      sufia.dashboard_units_url(*args)
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
    redirect_to view_context.unit_catalog_path @unit
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
    @membership = Membership.new(unit: @unit)
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(create_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(update_params)
        format.html { redirect_to @unit, notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_unit
    @unit = Unit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def create_params
    params.require(:unit).permit(:name, :description, :address, :phone, :fax, :email, :url, :key, :image, :visible,
                                 memberships_attributes: [:id, :user_id, :level, :_destroy])
  end

  def update_params
    create_params.except(:key)
  end
end

app/helpers/units_helper.rb
module UnitsHelper
  def unit_name(unit)
    if unit.is_a? Unit
      unit.name
    else
      Unit.find_by_key(unit).try(:name)
    end
  end

  def unit_catalog_path(unit)
    key = unit.is_a?(Unit) ? unit.key : unit
    main_app.search_catalog_path(f: { 'unit_sim' => [key] })
  end
end

app/views/units/_form.html.erb
<%= simple_form_for @unit do |f| %>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"><strong>Unit information</strong></div>
      <div class="panel-body">
        <%= f.input :name, label: "Unit name" %>
        <%= f.input :description %>
        <%= f.input :contact_person, label: "Contact Person" %>
        <%= f.input :address, label: "Address" %>
        <%= f.input :phone, label: "Telephone"  %>
        <%= f.input :fax, label: "Fax"  %>
        <%= f.input :email, label: "Email" %>
        <%= f.input :url, label: "Primary URL" %>
        <%= f.input :image, as: :file %>
        <%= f.input :visible %>  
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div id="memberships">
      <div class="panel panel-default">
        <div class="panel-heading"><strong>Members</strong></div>
        <div class="panel-body">
          <%= f.simple_fields_for :memberships do |membership| %>
            <%= render "membership_fields", :f => membership %>
          <% end %>
          <div class="links">
            <%= link_to_add_association f, :memberships, class: "btn btn-success" do %>
              <span class="sr-only">Add member to unit</span><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= f.button :submit %>
<% end %>

app/views/units/_membership_fields.html.erb
<div class="nested-fields">
  <table class="table table-striped">
    <tr>
      <td>
      <%= f.input :user_id, collection: User.all, label_method: 'to_s', include_blank: "Please select a user", input_html: { class: 'form-control select2-field' } %>
      </td>
      <td>
      <%= f.input :level, collection: Membership.levels.map{|l| [l.titleize, l]}, include_blank: "Please select a level" %>
      </td>
      <td style="vertical-align: middle;">
      <%= link_to_remove_association f , class: "btn btn-danger" do %>
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
      <% end %>
      </td>
    </tr>
  </table>
</div>

app/views/units/_unit_info.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title"><%= unit.name %></h3>
  </div>
  <div class="panel-body">
    <div class="col-xs-12">
      <%= unit.description %>
    </div>
  </div>
</div>

app/views/units/_unit_info_search.html.erb
<div class="panel panel-info visible-xs">
  <div class="panel-heading">
    <span>Buscando en: </span><h1 class="panel-title"><a href="#collapse" data-toggle="collapse"><%= unit.name %></a></h1>
  </div>
</div>
<div class="panel panel-info hidden-xs">
  <div class="panel-heading">
    <span>Buscando en: </span><h1 class="panel-title"><a href="#collapse" data-toggle="collapse"><%= unit.name %></a></h1>
  </div>
  <div class="panel-collapse collapse <%= "in" unless @page_number > 1 %>" id="collapse">
  <div class="panel-body">
    <div class="col-md-2">
        <%= image_tag unit.image.url(:landing), class: "img-thumbnail img-responsive" %>
      </div>
    <div class="col-md-10">
      <div class="unit_description_search">
      <p><%= unit.description %></p>
    </div>
    </div>
  </div>
</div>
</div>

app/views/units/_unit_info_sidebar.html.erb
<!-- <div class="panel panel-info hidden-xs">
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= unit.name %>
      <%- if can? :update, unit %>
        <small class="pull-right"><%= link_to 'Editar', edit_unit_path(unit) %></small>
      <%- end %>
    </h1>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <% if unit.address? %><p><%= unit.address %></p><% end %>
        <% if unit.phone.present? %><p><i class="fa fa-phone" aria-hidden="true"></i>&nbsp;<%= unit.phone %></p><% end %>
        <% if unit.fax.present? %><p><i class="fa fa-fax" aria-hidden="true"></i>&nbsp;<%= unit.fax %></p><% end %>
        <% if unit.email.present? %><p><i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;<%= unit.email %></p><% end %>
        <% if unit.url.present? %><p><i class="fa fa-external-link" aria-hidden="true"></i>&nbsp;<%= link_to unit.url, unit.url %></p><% end %>
      </div>
    </div>
  </div>
</div> -->

app/views/units/_unit_overlay.html.erb
<div class="col-lg-6 col-md-12 col-sm-12 collection-image">
  <div class="media hidden-sm hidden-xs text-left">
    <div class="media-left">
      <%= link_to image_tag(unit.image.url(:landing), class: "img-thumbnail media-object media-object-homepage"), unit_catalog_path(unit) %>
    </div>
    <div class="media-body">
      <!-- <h3 class="media-heading"><%= link_to unit.name, unit, class: "coll-title-link" %></h3> -->
      <h3 class="media-heading"><%= link_to unit.name, unit_catalog_path(unit), class: "coll-title-link" %></h3>
      <p><%= unit.description %></p>
    </div>
  </div>
  <div class="hidden-lg hidden-md">
    <h3 class="coll-title"><%= link_to unit.name, unit_catalog_path(unit), class: "coll-title-link" %></h3>
    <%= link_to image_tag(unit.image.url(:landing), class: "img-thumbnail img-responsive"), unit_catalog_path(unit) %>
    <p class="small_paragraph xs_paragraph"><%= unit.description %></p>
    <p><%= link_to "Browse Collections", unit_catalog_path(unit), class: "btn btn-success" %></p>
  </div>
</div>

app/views/units/edit.html.erb
<% provide :page_title, "Edit Unit" %>

<h1 class="page-header">Edit <%= @unit.name %></h1>

<%= render 'form' %>

app/views/units/index.html.erb
<% provide :page_title, "Units" %>

<div class="clearfix">
  <h1 class="pull-left page-header">Units</h1>
  <%= link_to new_unit_path, class: 'btn btn-success pull-right', style: 'margin-top:40px;' do %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New unit
  <% end %>
</div>

<p>Units are responsible for managing objects in the digital repository.</p>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Members</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @units.each do |unit| %>
      <tr>
        <td><%= link_to unit.name, unit_catalog_path(unit) %></td>
        <td><%= unit.description %></td>
        <td><%= unit.members.count %></td>
        <td>
          <div class="btn-group">
            <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button" id="dropdownMenu_<%= unit.id %>" aria-haspopup="true">
              <span class="sr-only">Press to </span>
              Select an action <span class="caret" aria-hidden="true"></span>
            </button>
            <ul role="menu" class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu_<%= unit.id %>">
              <%- if can? :read, unit %>
                <li role="menuitem" tabindex="-1">
                  <%= link_to unit_catalog_path(unit), class: 'itemicon itemshow' do %>
                    <i class="glyphicon glyphicon-eye-open" aria-hidden="true"></i> View Unit
                  <% end %>
                </li>
              <%- end %>
              <%- if can? :update, unit %>
                <li role="menuitem" tabindex="-1">
                  <%= link_to edit_unit_path(unit), class: 'itemicon itemedit' do %>
                    <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i> Edit Unit
                  <% end %>
                </li>
              <%- end %>
              <%- if can? :delete, unit %>
                <li role="menuitem" tabindex="-1">
                  <%= link_to unit_path(unit), class: 'itemicon itemtrash', method: :delete, data: {confirm: "Are you sure?"} do %>
                    <i class="glyphicon glyphicon-trash" aria-hidden="true"></i> Delete Unit
                  <% end %>
                </li>
              <%- end %>
            </ul>
          </div>
        </td>
      </tr>
    <% end.empty? %>
      <tr><td colspan="4">No units have been created.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/units/new.html.erb
<% provide :page_title, "Create Unit" %>

<h1 class="page-header">Create new unit</h1>

<%= simple_form_for @unit do |f| %>
  <%= f.input :name, label: "Unit name" %>
  <%= f.input :key, label: "Unit key", help: "Short identifier ofr this unit. Only A-Z, a-z, and 0-9 are allowed" %>
  <%= f.input :description %>
  <%= f.input :contact_person, label: "Contact Person" %>
  <%= f.input :address, label: "Address" %>
  <%= f.input :phone, label: "Telephone"  %>
  <%= f.input :fax, label: "Fax"  %>
  <%= f.input :email, label: "Email" %>
  <%= f.input :url, label: "Primary URL" %>
  <%= f.input :image, as: :file %>
  <%= f.submit "Create" %>
  <%= link_to "Cancel", units_path, :class => 'btn btn-link' %>
<% end %>